site_name: 2020_5eI_Team4
nav:
    - 'Project Charter': 'Project Charter.md'
    - 'Software Requirements Specification': 'Software Requirements Specification.md'
    - 'Software Project Management Plan': 'Software Project Management Plan.md'
    - 'Project Model Canvas': 'canvas model.pdf'

    
theme:
    name: readthedocs

use_directory_urls: true
